name: Canary-Windows

on:
  schedule:
    - cron:  '0 14 * * *'
  workflow_dispatch:
    inputs:
      repo-id:
        description: 'staging repository id to test'
        required: false
        default: ''
      djl-version:
        description: 'djl version to test'
        required: false
        default: '0.16.0'

jobs:
  canary-test-windows:
    if: github.repository == 'deepjavalibrary/djl-demo'
    runs-on: windows-latest
    env:
      AWS_REGION: us-east-1
      DJL_STAGING: ${{github.event.inputs.repo-id}}
      DJL_VERSION: ${{github.event.inputs.djl-version}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test MXNet
        working-directory: canary
        run: |
          cmd /c "set DJL_ENGINE=mxnet-native-auto&& .\gradlew.bat clean run"
          cmd /c "rd /s /q %userprofile%\.djl.ai"
          # cmd /c "set DJL_ENGINE=mxnet-native-mkl&& .\gradlew.bat clean run"
          # cmd /c "rd /s /q %userprofile%\.djl.ai"
      - name: Test PyTorch
        working-directory: canary
        run: |
          cmd /c "set DJL_ENGINE=pytorch-native-auto&& .\gradlew.bat clean run"
          cmd /c "rd /s /q %userprofile%\.djl.ai"
          cmd /c "set DJL_ENGINE=pytorch-native-auto&& set PYTORCH_VERSION=1.8.1&& .\gradlew.bat clean run"
          cmd /c "rd /s /q %userprofile%\.djl.ai"
          cmd /c "set DJL_ENGINE=pytorch-native-auto&& set PYTORCH_VERSION=1.9.1&& .\gradlew.bat clean run"
          cmd /c "rd /s /q %userprofile%\.djl.ai"
          cmd /c "set DJL_ENGINE=pytorch-native-cpu&& .\gradlew.bat clean run"
          cmd /c "rd /s /q %userprofile%\.djl.ai"
          cmd /c "set DJL_ENGINE=pytorch-native-cpu&& set PT_VERSION=1.8.1&& .\gradlew.bat clean run"
          cmd /c "rd /s /q %userprofile%\.djl.ai"
          cmd /c "set DJL_ENGINE=pytorch-native-cpu&& set PT_VERSION=1.9.1&& .\gradlew.bat clean run"
      - name: Test TensorFlow
        working-directory: canary
        run: |
          cmd /c "set DJL_ENGINE=tensorflow-native-auto&& .\gradlew.bat clean run"
          cmd /c "rd /s /q %userprofile%\.djl.ai"
          cmd /c "set DJL_ENGINE=tensorflow-native-cpu&& .\gradlew.bat clean run"
          cmd /c "rd /s /q %userprofile%\.djl.ai"
      - name: Test OnnxRuntime
        working-directory: canary
        run: |
          cmd /c "set DJL_ENGINE=onnxruntime&& .\gradlew.bat clean run"
      - name: Test PaddlePaddle
        working-directory: canary
        run: |
          cmd /c "set DJL_ENGINE=paddlepaddle-native-auto&& .\gradlew.bat clean run"
          cmd /c "rd /s /q %userprofile%\.djl.ai"
          cmd /c "set DJL_ENGINE=paddlepaddle-native-cpu&& .\gradlew.bat clean run"
          cmd /c "rd /s /q %userprofile%\.djl.ai"
      # DLR doesn't support Windows
      # TFLite doesn't support Windows
      # Xgboost doesn't support Windows
