name: DJL Demo Nightly test

on:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:


jobs:
  compile-test:
    if: github.repository == 'deepjavalibrary/djl-demo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
      - name: Compile all gradle projects
        run: ./gradlew build
      - name: Compile Apache Beam
        working-directory: apache-beam/ctr-prediction
        run: mvn package
      - name: Compile EMR projects
        working-directory: aws
        run: |
          cd emr-distributed-inference/dataprocess && ./gradlew build && cd ../../
          cd emr-distributed-inference/image-classification-gpu && ./gradlew build && cd ../../
      - name: Compile Apache Camel
        working-directory: camel-djl
        run: mvn package
      - name: Compile graalvm
        working-directory: graalvm
        run: ./mvnw package
      - name: Compile Quarkus
        working-directory: quarkus
        run: |
          cd example && ./mvnw package && cd ..
          cd extension && mvn package install && cd ..
          cd extension-example && ./mvnw package

